### ISSUE TITLE
Arbitrary "Config maps are empty. Fatal!" error

### ISSUE THREAD

**Issue by mnymkr** [evuraan/Swipe#11]
When using the config generated with `-sampleCfg`, the program runs fine. But when I edit the config to suit my need, it starts to show `Config maps are empty. Fatal!` and refuses to run.

I tried deleting every touch screen event in the config and it runs just fine.
I deleted 5 finger touchpad events and it runs just fine.
I deleted 4 finger touchpad events one by one and it runs just fine until the last 4 finger touchpad event is deleted. The program freaks out and shows the error.

**Comment by mnymkr** [comment]
Here's the content of the config file i used to test:

```
Sample Config: 
# 2 Button Touchpad 
2right: "KEY_LEFTALT + KEY_LEFT"
2left:  "KEY_LEFTALT + KEY_RIGHT"

# 3 Button Touchpad Gestures:
3right: "KEY_LEFTALT + KEY_LEFT"
3left:  "KEY_LEFTALT + KEY_RIGHT"
3up:    "KEY_SPACE"
3down:  "KEY_LEFTSHIFT + KEY_SPACE"

# 4 Button Touchpad Gestures:





# 5 - Touchscreens


touch2left: "KEY_LEFTALT + KEY_LEFT"
touch2right: "KEY_LEFTALT + KEY_RIGHT"


```

**Comment by evuraan** [comment]
Try with [Swipe/10a.5](https://github.com/evuraan/Swipe/tree/sep_2024/evtmaps/bin)
