### ISSUE TITLE
[Question] swipe from edge or to edge

### ISSUE THREAD

**Issue by lVentus** [evuraan/Swipe#2]
Great job! And would you like to consider about swipe from edge or to the edge? like a ipad or a phone, swipe up from bottom has a different function from swipe up.

**Comment by evuraan** [comment]
An easier approach for you would be to assign a two-finger gesture for one action and a three-finger gesture for another action. You can use up to four fingers for gestures. Keep in mind that we have to support various touchpads on many different laptops and devices. iPads and similar devices have stricter manufacturing standards, which makes their dimensions more uniform.   

At the moment, there are no plans to implement this, but you are welcome to submit a pull request.
