### ISSUE TITLE
Touchsceen - Multi finger touch gestures

### ISSUE THREAD

**Issue by Ka1zza** [evuraan/Swipe#4]
Hi There,
Love Swipe! Responsive and easy to configure!
Touchscreen gestures seem a bit lacking though. I see there are multiple speeds/fingers in the config. But they don't seem to work. Running Swipe in debug mode I can see the gestures are recognised. MED_UP/DOWN for 2 finger and FAST for 3 finger but no events are handled.

Are there plans to add this feature for horizontal touchscreen swipes as well? Or at least have Swipe ignore 1 finger touchsceen swipes?

Thanks for all your hard work!

Current Touchsceen mapping:
5right:      "KEY_LEFTALT + KEY_RIGHT"
5left:       "KEY_LEFTALT + KEY_LEFT"
5up:         "KEY_RESERVED"
5mediumUp:   "KEY_LEFTMETA + KEY_I"
5mediumDown: "KEY_LEFTMETA + KEY_I"
5down:       ""KEY_RESERVED"
5fastup:     "KEY_LEFTMETA + KEY_I"
5fastdown:   "KEY_LEFTMETA + KEY_I"

Debug:

> Sat Aug 19 17:45:11 2023 Swipe/7.2a movedTo: RIGHT
Sat Aug 19 17:45:11 2023 Swipe/7.2a fingers: 1
Sat Aug 19 17:45:11 2023 Swipe/7.2a startx :42.13, endx: 42.43
Sat Aug 19 17:45:11 2023 Swipe/7.2a starty: 67.03, endy: 67
Sat Aug 19 17:45:11 2023 Swipe/7.2a xdelta: 0.29999999999999716, ydelta: -0.030000000000001137, abs(xd): 0.29999999999999716, abs(yd): 0.030000000000001137
Sat Aug 19 17:45:11 2023 Swipe/7.2a combo: false
Sat Aug 19 17:45:11 2023 Swipe/7.2a touchLen: 23
Sat Aug 19 17:45:11 2023 [C] [emit] emitted 24 bytes type 1 code 56
Sat Aug 19 17:45:11 2023 [C] [emit] emitted 24 bytes type 1 code 106
Sat Aug 19 17:45:11 2023 [C] [emit] emitted 24 bytes type 0 code 0
Sat Aug 19 17:45:11 2023 [C] [emit] emitted 24 bytes type 1 code 56
Sat Aug 19 17:45:11 2023 [C] [emit] emitted 24 bytes type 1 code 106
Sat Aug 19 17:45:11 2023 [C] [emit] emitted 24 bytes type 0 code 0
Sat Aug 19 17:45:11 2023 [C] [handleEvents] Handled 2 events
Sat Aug 19 17:45:11 2023 Swipe/7.2a Gesture type 5, intent: RIGHT, cmd: KEY_LEFTALT + KEY_RIGHT
Sat Aug 19 17:45:16 2023 Swipe/7.2a movedTo: MED_DOWN
Sat Aug 19 17:45:16 2023 Swipe/7.2a fingers: 2
Sat Aug 19 17:45:16 2023 Swipe/7.2a startx :53.19, endx: 53.18
Sat Aug 19 17:45:16 2023 Swipe/7.2a starty: 39.89, endy: 40.05
Sat Aug 19 17:45:16 2023 Swipe/7.2a xdelta: -0.00999999999999801, ydelta: 0.1599999999999966, abs(xd): 0.00999999999999801, abs(yd): 0.1599999999999966
Sat Aug 19 17:45:16 2023 Swipe/7.2a touchLen: 30
Sat Aug 19 17:45:18 2023 Swipe/7.2a movedTo: FAST_DOWN
Sat Aug 19 17:45:18 2023 Swipe/7.2a fingers: 3
Sat Aug 19 17:45:18 2023 Swipe/7.2a startx :69.79, endx: 69.81
Sat Aug 19 17:45:18 2023 Swipe/7.2a touchLen: 26
Sat Aug 19 17:45:18 2023 Swipe/7.2a starty: 34.27, endy: 34.41
Sat Aug 19 17:45:18 2023 Swipe/7.2a xdelta: 0.01999999999999602, ydelta: 0.13999999999999346, abs(xd): 0.01999999999999602, abs(yd): 0.13999999999999346
Sat Aug 19 17:45:19 2023 Swipe/7.2a movedTo: FAST_UP
Sat Aug 19 17:45:19 2023 Swipe/7.2a fingers: 3
Sat Aug 19 17:45:19 2023 Swipe/7.2a touchLen: 27
Sat Aug 19 17:45:19 2023 Swipe/7.2a startx :51.78, endx: 51.78
Sat Aug 19 17:45:19 2023 Swipe/7.2a starty: 71.6, endy: 71.46
Sat Aug 19 17:45:19 2023 Swipe/7.2a xdelta: 0, ydelta: -0.14000000000000057, abs(xd): -0, abs(yd): 0.14000000000000057

**Comment by evuraan** [comment]
the gesture labels had mismatches, I've pushed a fix in: https://github.com/evuraan/Swipe/tree/touchstuff/bin
Please give it a try and let me know if it works.

**Comment by evuraan** [comment]
> Or at least have Swipe ignore 1 finger touchsceen swipes?

This is interesting -  please expand more on your use case? 
Firefox on my end ignores 1 finger touchscreen gestures by default, but I see that chromium and edge et al do act on those. 
So, a capability to mute certain touchscreen events will suffice?

**Comment by Ka1zza** [comment]
Thanks for getting back to me! I've just seen this and will test the fix shortly.

> This is interesting - please expand more on your use case?

I use a dell xps 2in1 and would like to set it up so I can use it entirely by touch when needed.
I'd like to set different gestures for touchsceen horizontal swipes. Currently Swipe seems to recognise 1,2,3 finger swipes as the one gesture (5left and 5right). I'd set Swipe to trigger "Back/Forward" for all apps with KEY_LEFTALT + KEY_RIGHT/KEY_LEFT which works great. But I want it to only trigger with a 3 finger gesture only, not 1 or 2 fingers. I've used a GNOME extension that changes the default switch desktop swipes to 4 finger so there's no conflict there.

> So, a capability to mute certain touchscreen events will suffice?

Muting certain events would be handy.  Oh, would it also be possible for the config to be loaded without certain key mappings set? I guess that would be part of muting certain events in a way?

Swipe is the only program I've found so far that works reliably and globally.  Great work!

**Comment by Ka1zza** [comment]
> the gesture labels had mismatches, I've pushed a fix in: https://github.com/evuraan/Swipe/tree/touchstuff/bin 
> Please give it a try and let me know if it works.

Just merged the changes, UP/DOWN touchscreen gestures now working as intended! Also will now load an incomplete key mapping. Thanks!

To simplify my above comment all I really want is to set LEFT/RIGHT touchscreen gestures the same as the UP/DOWN gestures. Separate 1,2 and 3 finger gestures.

**Comment by evuraan** [comment]
Here's a new build (in a new branch) that extracts individual touch events, it will let you mute or define actions for each type:

https://github.com/evuraan/Swipe/tree/touchEvents/bin

Please try it out and let me know, I will merge it to master at that time:

![image](https://github.com/evuraan/Swipe/assets/39205936/3c3e38e7-02fb-41ef-b233-b42c50bdc622)

**Comment by Ka1zza** [comment]
It works! Awesome!! I feel like you're making the app just for me XD
(I sent a donation via your website the other day, hopefully it comes through and is enough for a drink!)

I tested with the following conf
![image](https://github.com/evuraan/Swipe/assets/94217495/d097011b-95f4-43c1-a590-434ab47f6e2b)

I was able to reliably type out "abcdefghijklmn" and navigate up and down. 
Great work! Please let me know if there's anything else I can help test later down the track if you keep working on this.

**Comment by evuraan** [comment]
Thank you for the kind words and the donation is much appreciated! 

(Merged to main, released as `v8.0a`.)
