### ISSUE TITLE
Touchscreen gestures stop working when touchpad is disconnected

### ISSUE THREAD

**Issue by Ka1zza** [evuraan/Swipe#5]
Hey there, 

Since the last update its been awesome, just what I've been looking for. 

This issue is likely only a problem on 2-in-1 laptops. When I fold the display back my device (XPS 13") switches to tablet mode, disconnecting the keyboard and touchpad to avoid unwanted interactions. When this happens swipe stops registering touchscreen gestures as well. 

EDIT: Did further testing, looks like the gestures are still registered by Swipe, but nothing happens. Is it perhaps there's no keyboard?

Is there any way around this? I understand it may be difficult to test without a similar device.

Cheers
Kai

**Comment by evuraan** [comment]
Will this work?

![frameworks-1697304499863669578](https://github.com/evuraan/Swipe/assets/39205936/d8ceb988-6b8c-4f69-b1f6-20360a6ee9cd)

**Comment by Ka1zza** [comment]
Restarting swipe and running after my 2 in 1 was in tablet mode didn't seem to make a difference.

I did find a work around though. I have input mapper installed and it shows up as a kbd device "event20" When I tell swipe to use that input with "-i /dev/..." it seems to work when in tablet mode still.

**Comment by evuraan** [comment]
can you show o/p of `swipe -a`?

**Comment by Ka1zza** [comment]
sorry for the delay

```
Available: 22 devices
/dev/input/event0:	Lid Switch
/dev/input/event1:	Power Button
/dev/input/event2:	Sleep Button
/dev/input/event3:	Power Button
/dev/input/event4:	AT Translated Set 2 keyboard
/dev/input/event5:	SynPS/2 Synaptics TouchPad
/dev/input/event6:	DLL077A:01 06CB:76AF Mouse
/dev/input/event7:	Wacom HID 4831 Pen
/dev/input/event8:	Wacom HID 4831 Finger
/dev/input/event9:	Video Bus
/dev/input/event10:	Intel HID events
/dev/input/event11:	DLL077A:01 06CB:76AF Touchpad
/dev/input/event12:	Intel Virtual Buttons
/dev/input/event13:	Intel Virtual Switches
/dev/input/event14:	PC Speaker
/dev/input/event15:	Dell WMI hotkeys
/dev/input/event16:	HDA Intel PCH Headphone Mic
/dev/input/event17:	HDA Intel PCH HDMI/DP,pcm=3
/dev/input/event18:	HDA Intel PCH HDMI/DP,pcm=7
/dev/input/event19:	HDA Intel PCH HDMI/DP,pcm=8
/dev/input/event20:	input-remapper keyboard
/dev/input/event21:	input-remapper Wacom HID 4831 Pen forwarded
```

Event20 seems to be the only device that lets swipe keep working when my laptop is folded back in tablet mode. I tried all the ones that seem to be keyboards.
```
swipe -i /dev/input/event20 -c ~/.config/swipe/swipe.conf
```

**Comment by evuraan** [comment]
Spot on! The other option would be to write a devmapper trigger, or a loop script like:

```bash
#!/bin/bash

cd /someFolderWhereSwipeLives

# Initial MD5 sum
prev_md5=$(./swipe -a | md5sum)

while true; do
    # Compute the new MD5 sum
    new_md5=$(./swipe -a | md5sum)

    # Compare the new MD5 sum with the previous one
    if [[ "$new_md5" != "$prev_md5" ]]; then
        # If the MD5 sum changed, kill the swipe process and restart it
        pkill -9 swipe
        ./swipe &
        
        # Update the MD5 sum
        prev_md5=$new_md5
    fi

    # Wait for 5 seconds before the next iteration
    sleep 5
done
```
