### ISSUE TITLE
Pinch to zoom seems to break Swipe "Error 3.1 - disabling further notifications"

### ISSUE THREAD

**Issue by sjftech** [evuraan/Swipe#6]
Hello

First I'd like to say how amazing Swipe is as it bridges a gap between Linux and Windows that shouldn't be there IMO!

However, when I pinch to zoom after launching Swipe, it works initially and then after one or two times of pinching and zooming, it appears to break Swipe and throws up the error of "Error 3.1 - disabling further notifications".

I'm on Pop!_OS 22.04 on a Lenovo Legion 7 laptop.

**Comment by evuraan** [comment]
Try with `-q`  or `--noIndicator` option to disable panel indicator? If problem persists, please provide debug log, run with `-d` flag. 

> I'm on Pop!_OS 22.04


Glad to hear its being used on many variants!

**Comment by sjftech** [comment]
Hi, thanks for responding!

I tried with -q and --noIndicator and it still does the same.

Here's a log with -d.

./swipe -d
Copyright © 2021 Evuraan <evuraan@gmail.com>. All rights reserved.
This program comes with ABSOLUTELY NO WARRANTY.
Fri Nov 17 12:41:43 2023 Swipe/8.0a Howdy!
Fri Nov 17 12:41:43 2023 Swipe/8.0a keyboard device: /dev/input/event7
Fri Nov 17 12:41:43 2023 [C] [getFd] fd opened: 3
Fri Nov 17 12:41:43 2023 Swipe/8.0a About to run stdbuf -oL /usr/libexec/libinput/libinput-debug-events
Fri Nov 17 12:41:43 2023 Swipe/8.0a pid: 3775
Fri Nov 17 12:41:47 2023 Swipe/8.0a POINTER_SCROLL_FINGER intent: RIGHT
Fri Nov 17 12:41:47 2023 Swipe/8.0a combo: false
Error 3.1 - disabling further notifications
Fri Nov 17 12:41:47 2023 [C] [emit] emitted 24 bytes type 1 code 56
Fri Nov 17 12:41:47 2023 [C] [emit] emitted 24 bytes type 1 code 105
Fri Nov 17 12:41:47 2023 [C] [emit] emitted 24 bytes type 0 code 0
Fri Nov 17 12:41:47 2023 [C] [emit] emitted 24 bytes type 1 code 56
Fri Nov 17 12:41:47 2023 [C] [emit] emitted 24 bytes type 1 code 105
Fri Nov 17 12:41:47 2023 [C] [emit] emitted 24 bytes type 0 code 0
Fri Nov 17 12:41:47 2023 [C] [handleEvents] Handled 2 events
Fri Nov 17 12:41:47 2023 Swipe/8.0a Gesture type 2, intent: RIGHT, cmd: KEY_LEFTALT + KEY_LEFT
Fri Nov 17 12:41:48 2023 Swipe/8.0a POINTER_SCROLL_FINGER intent: LEFT
Fri Nov 17 12:41:48 2023 Swipe/8.0a combo: false
Fri Nov 17 12:41:48 2023 [C] [emit] emitted 24 bytes type 1 code 56
Fri Nov 17 12:41:48 2023 [C] [emit] emitted 24 bytes type 1 code 106
Fri Nov 17 12:41:48 2023 [C] [emit] emitted 24 bytes type 0 code 0
Fri Nov 17 12:41:48 2023 [C] [emit] emitted 24 bytes type 1 code 56
Fri Nov 17 12:41:48 2023 [C] [emit] emitted 24 bytes type 1 code 106
Fri Nov 17 12:41:48 2023 [C] [emit] emitted 24 bytes type 0 code 0
Fri Nov 17 12:41:48 2023 [C] [handleEvents] Handled 2 events
Fri Nov 17 12:41:48 2023 Swipe/8.0a Gesture type 2, intent: LEFT, cmd: KEY_LEFTALT + KEY_RIGHT

**Comment by evuraan** [comment]
Despite that innocuous error, it is still intercepting your events (1,2 in screenshot).  You still see `swipe` running, and not crashing, yeah?

![image](https://github.com/evuraan/Swipe/assets/39205936/2d49b161-9844-46f4-a2dd-51ba6c0f869d)

Try with another input device instead of your default pick `/dev/input/event7`.  See [this](https://github.com/evuraan/Swipe/issues/5#issuecomment-1800922957) post. 

## Edit: 

I've pushed a branch that disables the conduit if `-q` is set, please try this binary if interested and let me know:
https://github.com/evuraan/Swipe/tree/suppress_notification_on_noIndicator/bin
