### ISSUE TITLE
Implement ability to excute a command.

### ISSUE THREAD

**Issue by lokman2k5** [evuraan/Swipe#8]
I'd like to have the option to be able to execute a command when an event is triggered (for example putting a command in front of touch3down in the config file should execute the command when swiping 3 fingers downwards).

**Comment by evuraan** [comment]
I tried some of that [earlier](https://github.com/evuraan/Swipe/commit/935c99c448b5dda792a2783ed8d0ff7aedd3377a) but abandoned that route soon after. 

Instead  try [mapping a keyboard shortcut to your command](https://github.com/evuraan/mintPiper?tab=readme-ov-file#add-a-keyboard-shortcut) and map that shortcut to an event:

```bash
4left:  "KEY_LEFTALT + KEY_RIGHTCTRL + KEY_P"
```
